# Generated by Django 4.0.4 on 2022-05-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
