# Generated by Django 4.0.4 on 2022-06-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='dieta',
            field=models.BooleanField(default=False),
        ),
    ]
