<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-06-01 18:59
=======
# Generated by Django 4.0.4 on 2022-06-01 18:45
>>>>>>> 87239b6ad5f0524e53c816cf239c08d19bdb674b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='dieta',
            field=models.BooleanField(default=False),
        ),
    ]
