# Generated by Django 4.0.4 on 2022-06-03 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutri', '0002_dieta_dieta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprimirDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_11', models.CharField(max_length=255)),
                ('quant_11', models.IntegerField()),
                ('ref_13', models.CharField(max_length=255)),
                ('quant_13', models.IntegerField()),
                ('ref_12', models.CharField(max_length=255)),
                ('quant_12', models.IntegerField()),
                ('ref_22', models.CharField(max_length=255)),
                ('quant_22', models.IntegerField()),
                ('ref_31', models.CharField(blank=True, max_length=255)),
                ('quant_31', models.IntegerField(blank=True)),
                ('ref_32', models.CharField(blank=True, max_length=255)),
                ('quant_32', models.IntegerField(blank=True)),
                ('ref_33', models.CharField(blank=True, max_length=255)),
                ('quant_33', models.IntegerField(blank=True)),
                ('ref_41', models.CharField(blank=True, max_length=255)),
                ('quant_41', models.IntegerField(blank=True)),
                ('ref_42', models.CharField(blank=True, max_length=255)),
                ('quant_42', models.IntegerField(blank=True)),
                ('ref_43', models.CharField(blank=True, max_length=255)),
                ('quant_43', models.IntegerField(blank=True)),
                ('ref_51', models.CharField(blank=True, max_length=255)),
                ('quant_51', models.IntegerField(blank=True)),
                ('ref_52', models.CharField(blank=True, max_length=255)),
                ('quant_52', models.IntegerField(blank=True)),
                ('ref_53', models.CharField(blank=True, max_length=255)),
                ('quant_53', models.IntegerField(blank=True)),
                ('ref_61', models.CharField(blank=True, max_length=255)),
                ('quant_61', models.IntegerField(blank=True)),
                ('ref_62', models.CharField(blank=True, max_length=255)),
                ('quant_62', models.IntegerField(blank=True)),
                ('ref_63', models.CharField(blank=True, max_length=255)),
                ('quant_63', models.IntegerField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
