# Generated by Django 4.0.4 on 2022-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0005_alter_imprimirdieta_quant_32_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_32',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_33',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_41',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_42',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_43',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_51',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_52',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_53',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_61',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_62',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_63',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_31',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_32',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_33',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_41',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_42',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_43',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_51',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_52',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_53',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_61',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_62',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_63',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
