# Generated by Django 4.0.4 on 2022-06-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0006_rename_ref_11_imprimirdieta_ref_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='caloria_dieta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dieta',
            name='carboidratos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dieta',
            name='gasto_dia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dieta',
            name='gordura',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dieta',
            name='proteina',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dieta',
            name='tmb',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
