<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-06-07 17:20
=======
# Generated by Django 4.0.4 on 2022-06-07 16:49
>>>>>>> 388081777ed6d9e104c9a407f7688da9e700732f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0007_dieta_caloria_dieta_dieta_carboidratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_3',
<<<<<<< HEAD
            field=models.CharField(blank=True, default='', max_length=255),
=======
            field=models.CharField(blank=True, max_length=255),
>>>>>>> 388081777ed6d9e104c9a407f7688da9e700732f
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_4',
<<<<<<< HEAD
            field=models.CharField(blank=True, default='', max_length=255),
=======
            field=models.CharField(blank=True, max_length=255),
>>>>>>> 388081777ed6d9e104c9a407f7688da9e700732f
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_5',
<<<<<<< HEAD
            field=models.CharField(blank=True, default='', max_length=255),
=======
            field=models.CharField(blank=True, max_length=255),
>>>>>>> 388081777ed6d9e104c9a407f7688da9e700732f
        ),
    ]
