<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-06-07 17:20
=======
# Generated by Django 4.0.4 on 2022-06-07 16:49
>>>>>>> be5d0afa8b02f4e6794258502e0b5f06f25eff57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0007_dieta_caloria_dieta_dieta_carboidratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
