# Generated by Django 4.0.4 on 2022-06-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0008_alter_imprimirdieta_ref_3_alter_imprimirdieta_ref_4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imprimirdieta',
            old_name='ref_1',
            new_name='ref_11',
        ),
        migrations.RenameField(
            model_name='imprimirdieta',
            old_name='ref_2',
            new_name='ref_12',
        ),
        migrations.RenameField(
            model_name='imprimirdieta',
            old_name='ref_3',
            new_name='ref_33',
        ),
        migrations.RenameField(
            model_name='imprimirdieta',
            old_name='ref_4',
            new_name='ref_43',
        ),
        migrations.RenameField(
            model_name='imprimirdieta',
            old_name='ref_5',
            new_name='ref_53',
        ),
        migrations.RenameField(
            model_name='imprimirdieta',
            old_name='ref_6',
            new_name='ref_63',
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_11',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_12',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_13',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_21',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_22',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_23',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_31',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_32',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_33',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_41',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_42',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_43',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_51',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_52',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_53',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_61',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_62',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='quant_63',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_13',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_21',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_22',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_23',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_31',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_32',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_41',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_42',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_51',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_52',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_61',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imprimirdieta',
            name='ref_62',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
