# Generated by Django 4.0.4 on 2022-06-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0009_rename_ref_1_imprimirdieta_ref_11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_21',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_22',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_23',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_31',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_32',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_33',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_41',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_42',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_43',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_51',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_52',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_53',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_61',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_62',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_63',
            field=models.IntegerField(default=0),
        ),
    ]
