# Generated by Django 4.0.4 on 2022-06-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0010_alter_imprimirdieta_quant_11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_31',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_32',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_33',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_41',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_42',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_43',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_51',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_52',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_53',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_61',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_62',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='quant_63',
            field=models.IntegerField(blank=True),
        ),
    ]
