# Generated by Django 4.0.4 on 2022-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0011_alter_imprimirdieta_quant_31_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_33',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_43',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imprimirdieta',
            name='ref_53',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
